version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: agentic-workflow-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: agentic_workflow
    volumes:
      - mongodb_data:/data/db
    networks:
      - agentic-workflow

  # Optional: MongoDB Express for database management
  mongo-express:
    image: mongo-express:latest
    container_name: agentic-workflow-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - agentic-workflow

volumes:
  mongodb_data:

networks:
  agentic-workflow:
    driver: bridge